name: Deploy

# only deploy on release
on:
  push:
    branches:
      - master

jobs:
  online:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Setup repo (prod mode)
        run: npm run setup:prod -- --yes
      - name: Setup web specific parts
        run: npm run setup:web
      - name: Install Surge CI tool
        run: npm install surge --global
      - name: Linting
        run: npm run lint
      - name: Deploy to surge
        run: surge --project ./core/online/dist --domain magic-circle.surge.sh
        env:
          SURGE_EMAIL: ${{ secrets.SURGE_EMAIL }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
