name: Test

on: [push]

jobs:
  linting:
    runs-on: macos-latest
    strategy:
      matrix:
        stage: [dev, prod]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Setup repo (dev mode)
        run: |
          npm run setup:${{ matrix.stage }} -- --yes
      - name: Linting
        run: npm run lint

  example_simple:
    runs-on: macos-latest
    strategy:
      matrix:
        stage: [dev, prod]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Setup repo (dev mode)
        run: |
          npm run setup:${{ matrix.stage }} -- --yes
      - name: Run simple example
        env:
          CI: true
        run: npm run example simple

  example_custom-plugin:
    runs-on: macos-latest
    strategy:
      matrix:
        stage: [dev, prod]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Setup repo (dev mode)
        run: |
          npm run setup:${{ matrix.stage }} -- --yes
      - name: Run example with custom plugin
        env:
          CI: true
        run: npm run example custom-plugin

  example_embed:
    runs-on: macos-latest
    strategy:
      matrix:
        stage: [dev, prod]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Setup repo (dev mode)
        run: |
          npm run setup:${{ matrix.stage }} -- --yes
      - name: Run example with embedded files
        env:
          CI: true
        run: npm run example simple embed
