name: Test

on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  linting:
    runs-on: linux-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Setup repo
        run: npm i
      - name: Linting
        run: npm run lint
  build:
    runs-on: linux-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Setup repo
        run: npm i
      - name: Linting
        run: npm run build:dev
