name: Test

on: [push]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup repo (dev mode)
        run: |
          npm run setup:dev -- --yes
      - name: Linting
        run: npm run lint
      - name: Run an example
        run: npm run example simple
